# Generated by Django 2.2.1 on 2019-05-29 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190519_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(default='user', max_length=30)),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('job_role', models.CharField(max_length=30)),
                ('job_desc', models.TextField()),
                ('username', models.CharField(max_length=10)),
                ('posted_on', models.DateTimeField()),
                ('total_applications', models.IntegerField(default=0)),
                ('active_applications', models.IntegerField(default=0)),
                ('offers_made', models.IntegerField(default=0)),
                ('pending_feedbacks', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='hr',
            name='full_name',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
